# Generated by Django 3.2.3 on 2021-06-18 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210618_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_api_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
